Add missing newline
Fixes build:
  CC    target/arch/sparc64/boot.o
In file included from ../arch/sparc64/boot.c:14:
../include/libopenbios/forth_load.h:22:28: error: no newline at end of file

Signed-off-by: Blue Swirl <blauwirbel@gmail.com>

git-svn-id: svn://openbios.org/openbios/trunk/openbios-devel@718 f158a5a8-5612-0410-a976-696ce0be7e32